openapi: 3.0.2
info:
  title: Building data link API
  version: 1.0.0
servers:
  - url: /api/v1.0
paths:
  /link:
    post:
      operationId: LibTerrainRestApi.datalink.compute_link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputData'
      responses:
        '200':
          description: Data found and computed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnData'
        default:
          description: Any error happened during data processing

components:
  schemas:
    ReturnData:
      type: object
      properties:
        source:
          $ref: '#/components/schemas/Geometry'
        destination:
          $ref: '#/components/schemas/Geometry'
        maxSpeed:
          type: number
    InputData:
      type: object
      description: data needed by Rest service to process client request
      properties:
        area:
          type: string
          description: city or comune or province name
          minLength: 3
          maxLength: 40
        source:
          $ref: '#/components/schemas/Geometry'
        destination:
          $ref: '#/components/schemas/Geometry'
      required:
        - area
        - source
        - destination
    Geometry:
      type: object
      description: GeoJSon geometry
      properties:
        type:
          type: string
          description: the geometry type
          enum:
            - Point
        coordinates:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
      required:
        - type
        - coordinates

#      FeatureCollection:
#         type: object
#         description: GeoJSon Feature collection
#         properties:
#            type:
#               type: string
#               enum:
#                  - FeatureCollection
#            features:
#               type: array
#               minItems: 2
#               maxItems: 2
#               items:
#                  $ref: '#/components/schemas/Feature'
#         required:
#            - type
#            - features

#      Feature:
#         type: object
#         description: GeoJSon Feature
#         properties:
#            type:
#               type: string
#            properties:
#               type: object
#               enum:
#                  - Feature
#            geometry:
#               $ref: '#/components/schemas/Geometry'
#         required:
#            - type